stages:
  - build
  - deploy
 
build_staging:
  image: node:6.11.2
  stage: build
  variables:
   REACT_APP_API_URL: "https://pushdeployapi-staging.herokuapp.com"
  script:
    - echo "building.."
    - npm install
    - npm run build react
  artifacts:
    paths:
     - build/
  only:
  - staging

build_production:
  image: node:6.11.2
  stage: build
  variables:
   REACT_APP_API_URL: "https://pushdeployapi-prod.herokuapp.com"
  script:
    - echo "building.."
    - npm install
    - npm run build react
  artifacts:
    paths:
     - build/
  only:
  - master
  
deploy_staging:
  image: python:3.4.3
  stage: deploy
  variables:
    BUCKET_NAME: "staging.dashboard.pushdeploy.io"
  before_script:
    - pip install awscli
    - pip install -U awscli
  script:
    - echo "Deploying to staging.."
    - aws s3 sync --delete build "s3://${BUCKET_NAME}/"
  environment:
    name: staging
    url: https://staging.dashboard.pushdeploy.io
  only:
  - staging
  
deploy_production:
  image: python:3.4.3
  stage: deploy
  variables:
    BUCKET_NAME: "dashboard.pushdeploy.io"
  before_script:
    - pip install awscli
    - pip install -U awscli
  script:
    - echo "Deploying to production.."
    - aws s3 sync --delete build "s3://${BUCKET_NAME}/"
  environment:
    name: production
    url: https://dashboard.pushdeploy.io
  only:
  - master