stages:
  - build
  - deploy_staging
  - deploy_production
 
build:
  image: node:6.11.2
  stage: build
  script:
    - echo "building.."
    - npm install
    - npm run build react
  artifacts:
    paths:
     - build/

deploy_staging:
  image: python:3.4.3
  stage: deploy_staging
  variables:
    BUCKET_NAME: "staging.dashboard.pushdeploy.io"
  before_script:
    - pip install awscli
    - pip install -U awscli
  script:
    - echo "Deploying to staging"
    #- aws s3 rm "s3://${BUCKET_NAME}/*" --recursive
    #- aws s3 cp build "s3://${BUCKET_NAME}/" --recursive
    - aws s3 sync --delete --acl public-read build/* "s3://${BUCKET_NAME}/"
  environment:
    name: production
    url: https://stagin.dashboard.pushdeploy.io
  only:
  - staging
  
deploy_production:
  image: python:3.4.3
  stage: deploy_production
  variables:
    BUCKET_NAME: "dashboard.pushdeploy.io"
  before_script:
    - pip install awscli
    - pip install -U awscli
  script:
    - echo "Deploying to production"
    #- aws s3 rm "s3://${BUCKET_NAME}/*" --recursive
    #- aws s3 cp build "s3://${BUCKET_NAME}/" --recursive
    - aws s3 sync --delete --acl public-read build/* "s3://${BUCKET_NAME}/"
  environment:
    name: production
    url: https://dashboard.pushdeploy.io
  only:
  - master