apiVersion: v1
kind: Service
metadata:
  name: pushdeploy-dashboard
  namespace: default
  labels:
    app: pushdeploy-dashboard
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "false"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "e3846a2e-9ad9-4bd0-a892-af281fc54774"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
  selector:
    app: pushdeploy-dashboard